# Generated by Django 4.2.5 on 2024-02-10 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterField(
            model_name='buildingverification',
            name='state',
            field=models.IntegerField(default=-1, verbose_name='Фактический статус готовности'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 18, 27, 52, 655659, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
