# Generated by Django 4.2.5 on 2024-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type_building', models.CharField(max_length=127)),
                ('count_floor', models.IntegerField()),
                ('year_building', models.IntegerField()),
                ('document_building', models.CharField(max_length=10)),
                ('project_document', models.CharField(max_length=10)),
                ('status_building', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1)),
                ('image', models.ImageField(default='images/1.jpg', upload_to='images')),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('checking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('age', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Создана'), (2, 'На модерации'), (3, 'Опубликована'), (4, 'Закрыта'), (5, 'Удалёна')], default=1)),
                ('creation_time', models.DateField()),
                ('approving_date', models.DateField()),
                ('publication_date', models.DateField()),
            ],
            options={
                'db_table': 'checking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckingsBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'checkingsbuildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=31)),
                ('password', models.CharField(max_length=31)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
