# Generated by Django 4.2.5 on 2024-01-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckingsBuildings',
        ),
    ]
