# Generated by Django 4.2.5 on 2024-01-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_delete_checkingsbuildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingsBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'checkingsbuildings',
                'managed': False,
            },
        ),
    ]
